json.id workflow.id
json.account_id workflow.account_id
json.name workflow.name
json.description workflow.description
json.active workflow.active?
json.graph workflow.graph
json.created_on workflow.created_at.to_i
json.updated_on workflow.updated_at.to_i
json.created_by_id workflow.created_by_id
json.updated_by_id workflow.updated_by_id
